In [3]:
import pandas as pd

df = pd.read_excel('fr-en-annuaire-education.xlsx', engine='openpyxl')

In [4]:
df

,Identifiant_de_l_etablissement,Nom_etablissement,Type_etablissement,Statut_public_prive,Adresse_1,Adresse_2,Adresse_3,Code_postal,Code_commune,Nom_commune,...,libelle_nature,Code_type_contrat_prive,PIAL,etablissement_mere,type_rattachement_etablissement_mere,code_circonscription,code_zone_animation_pedagogique,libelle_zone_animation_pedagogique,code_bassin_formation,libelle_bassin_formation
0,0631348Y,Ecole élémentaire privée Pensionnat Sainte Anne,Ecole,Privé,25 route des Puys,BP 5,63870 ORCINES,63870,63263,Orcines,...,ECOLE DE NIVEAU ELEMENTAIRE,30,0631081H,NaN,NaN,0631011G,NaN,NaN,0663C,CLERMONT NORD
1,0631425G,Ecole primaire la Dordogne,Ecole,Public,Quai Féron,NaN,63150 LA BOURBOULE,63150,63047,La Bourboule,...,ECOLE DE NIVEAU ELEMENTAIRE,99,0630056U,NaN,NaN,0631011G,NaN,NaN,0663C,CLERMONT NORD
2,0631433R,Ecole maternelle d'application Aristide Briand,Ecole,Public,6 rue Saint Simon,NaN,63000 CLERMONT FERRAND,63000,63113,Clermont-Ferrand,...,ECOLE MATERNELLE D APPLICATION,99,0631410R,NaN,NaN,0631014K,NaN,NaN,0663A,CLERMONT CENTRE
3,0631441Z,Ecole primaire Turelet,Ecole,Public,106 RUE DE LA FRATERNITE,NaN,63300 THIERS,63300,63430,Thiers,...,ECOLE DE NIVEAU ELEMENTAIRE,99,0631238D,NaN,NaN,0631020S,NaN,NaN,06635,THIERS
4,0631485X,Ecole maternelle Jules Verne,Ecole,Public,1 BIS RUE D'AULTERIBE,NaN,63100 CLERMONT FERRAND,63100,63113,Clermont-Ferrand,...,ECOLE MATERNELLE,99,0631199L,NaN,NaN,0631013J,NaN,NaN,0663C,CLERMONT NORD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68931,0730063X,Circonscription d'inspection du 1er degré de M...,Service Administratif,NaN,53 place de l'Hôtel de Ville,GROUPE SCOLAIRE,73600 MOUTIERS TARENTAISE,73600,73181,Moûtiers,...,CIRCONSCRIPTIONS INSPECTION EDUC NAT,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68932,0731102B,Circonscription d'inspection du 1er degré de C...,Service Administratif,NaN,131 avenue de Lyon,NaN,73018 CHAMBERY CEDEX,73018,73065,Chambéry,...,CIRCONSCRIPTIONS INSPECTION EDUC NAT,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68933,0731449D,Circonscription d'inspection du 1er degré de M...,Service Administratif,NaN,14 avenue de la gare,BP 79,73800 MONTMELIAN,73800,73171,Montmélian,...,CIRCONSCRIPTIONS INSPECTION EDUC NAT,99,NaN,NaN,NaN,NaN,NaN,NaN,08735,CHAMBERY
68934,0740076F,Circonscription d'inspection du 1er degré de B...,Service Administratif,NaN,126 rue des grandes chambrettes,NaN,74130 BONNEVILLE,74130,74042,Bonneville,...,CIRCONSCRIPTIONS INSPECTION EDUC NAT,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68935,0740079J,Circonscription d'inspection du 1er degré de T...,Service Administratif,NaN,6 avenue Saint-Francois de Sales,NaN,74200 THONON LES BAINS,74200,74281,Thonon-les-Bains,...,CIRCONSCRIPTIONS INSPECTION EDUC NAT,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.shape

(68936, 71)

In [6]:
ds.columns

NameError: name 'ds' is not defined

In [7]:
df.columns

Index(['Identifiant_de_l_etablissement', 'Nom_etablissement',
       'Type_etablissement', 'Statut_public_prive', 'Adresse_1', 'Adresse_2',
       'Adresse_3', 'Code_postal', 'Code_commune', 'Nom_commune',
       'Code_departement', 'Code_academie', 'Code_region', 'Ecole_maternelle',
       'Ecole_elementaire', 'Voie_generale', 'Voie_technologique',
       'Voie_professionnelle', 'Telephone', 'Fax', 'Web', 'Mail',
       'Restauration', 'Hebergement', 'ULIS', 'Apprentissage', 'Segpa',
       'Section_arts', 'Section_cinema', 'Section_theatre', 'Section_sport',
       'Section_internationale', 'Section_europeenne', 'Lycee_Agricole',
       'Lycee_militaire', 'Lycee_des_metiers', 'Post_BAC',
       'Appartenance_Education_Prioritaire', 'GRETA', 'SIREN_SIRET',
       'Fiche_onisep', 'position', 'Type_contrat_prive', 'Libelle_departement',
       'Libelle_academie', 'Libelle_region', 'coordX_origine',
       'coordY_origine', 'epsg_origine', 'nom_circonscription', 'latitude',
       'longitude', 'precision_localisation', 'date_ouverture',
       'date_maj_ligne', 'etat', 'ministere_tutelle', 'multi_uai',
       'rpi_concentre', 'rpi_disperse', 'code_nature', 'libelle_nature',
       'Code_type_contrat_prive', 'PIAL', 'etablissement_mere',
       'type_rattachement_etablissement_mere', 'code_circonscription',
       'code_zone_animation_pedagogique', 'libelle_zone_animation_pedagogique',
       'code_bassin_formation', 'libelle_bassin_formation'],
      dtype='str')

In [10]:
import pandas as pd

# Charger le fichier Excel
df = pd.read_excel('fr-en-annuaire-education.xlsx', engine='openpyxl')

# Colonnes utiles
colonnes_utiles = [
    'Nom_etablissement',
    'Type_etablissement',
    'Statut_public_prive',
    'Web',
    'Telephone',
    'Mail',
    'Code_postal',
    'Nom_commune',
    'Libelle_departement',
    'Libelle_academie'
]

df = df[colonnes_utiles]
df.head()

,Nom_etablissement,Type_etablissement,Statut_public_prive,Web,Telephone,Mail,Code_postal,Nom_commune,Libelle_departement,Libelle_academie
0,Ecole élémentaire privée Pensionnat Sainte Anne,Ecole,Privé,NaN,0473621046,ce.0631348Y@ac-clermont.fr,63870,Orcines,Puy-de-Dôme,Clermont-Ferrand
1,Ecole primaire la Dordogne,Ecole,Public,NaN,0473810425,ce.0631425G@ac-clermont.fr,63150,La Bourboule,Puy-de-Dôme,Clermont-Ferrand
2,Ecole maternelle d'application Aristide Briand,Ecole,Public,NaN,0473935287,ce.0631433R@ac-clermont.fr,63000,Clermont-Ferrand,Puy-de-Dôme,Clermont-Ferrand
3,Ecole primaire Turelet,Ecole,Public,NaN,0473802379,ce.0631441Z@ac-clermont.fr,63300,Thiers,Puy-de-Dôme,Clermont-Ferrand
4,Ecole maternelle Jules Verne,Ecole,Public,NaN,0473408822,ce.0631485X@ac-clermont.fr,63100,Clermont-Ferrand,Puy-de-Dôme,Clermont-Ferrand